apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies-enforce
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ghostlygeorge/pharia.git'
    targetRevision: enforce          #  enforce branch
    path: policies
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
